<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Meziantou.Analyzer" Version="3.0.294" />
    <PackageVersion Include="Roslynator.Analyzers" Version="5.0.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
    <PackageVersion Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" />
    <PackageVersion Include="NetFabric.Hyperlinq.Analyzer" Version="2.3.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
    <PackageVersion Include="MSTest" Version="4.0.2" />
    <PackageVersion Include="MSTest.Analyzers" Version="4.0.2" />
  </ItemGroup>
</Project>
