using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace WarpCLR.CSharp.Generators;

internal static class WarpCLRSourceWriter
{
    public static string Write(
        string manifest,
        ImmutableArray<WarpCLREntryModel> entries)
    {
        var source = new StringBuilder();
        Line(source, "// <auto-generated/>");
        Line(source, "#nullable enable");
        source.Append("[assembly: global::System.Reflection.AssemblyMetadataAttribute(");
        source.Append(SymbolDisplay.FormatLiteral("WarpCIL.Manifest", quote: true));
        source.Append(", ");
        source.Append(SymbolDisplay.FormatLiteral(manifest, quote: true));
        Line(source, ")]");

        foreach (IGrouping<string, WarpCLREntryModel> catalog in entries
                     .GroupBy(entry => $"{entry.NamespaceSource}\0{entry.CatalogName}")
                     .OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            WarpCLREntryModel first = catalog.First();
            bool hasNamespace = first.NamespaceSource.Length != 0;
            if (hasNamespace)
            {
                Line(source, $"namespace {first.NamespaceSource}");
                Line(source, "{");
            }

            string indent = hasNamespace ? "    " : string.Empty;
            Line(
                source,
                $"{indent}[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
            Line(
                source,
                $"{indent}{first.CatalogAccessibility} static class {first.CatalogName}");
            Line(source, $"{indent}{{");
            foreach (WarpCLREntryModel entry in catalog
                         .OrderBy(value => value.MethodIdentity, StringComparer.Ordinal))
            {
                WriteEntry(source, entry, indent + "    ");
            }

            Line(source, $"{indent}}}");
            if (hasNamespace)
            {
                Line(source, "}");
            }
        }

        return source.ToString();
    }

    private static void WriteEntry(
        StringBuilder source,
        WarpCLREntryModel entry,
        string indent)
    {
        string identity = SymbolDisplay.FormatLiteral(entry.Identity, quote: true);
        string inputCount = entry.InputBufferCount.ToString(CultureInfo.InvariantCulture);
        string scalarCount = entry.ScalarArgumentCount.ToString(CultureInfo.InvariantCulture);
        if (entry.Execution == 0)
        {
            Line(
                source,
                $"{indent}public static global::WarpCLR.CSharp.WarpMapEntry {entry.PropertyName} {{ get; }} =");
            Line(
                source,
                $"{indent}    new global::WarpCLR.CSharp.WarpMapEntry({identity}, {inputCount}, {scalarCount});");
            return;
        }

        string execution = entry.Execution switch
        {
            1 => "global::WarpCLR.CSharp.WarpExecution.ReduceWrappingSum",
            2 => "global::WarpCLR.CSharp.WarpExecution.ReduceMinimum",
            3 => "global::WarpCLR.CSharp.WarpExecution.ReduceMaximum",
            _ => $"(global::WarpCLR.CSharp.WarpExecution){entry.Execution.ToString(CultureInfo.InvariantCulture)}",
        };
        Line(
            source,
            $"{indent}public static global::WarpCLR.CSharp.WarpReductionEntry {entry.PropertyName} {{ get; }} =");
        Line(
            source,
            $"{indent}    new global::WarpCLR.CSharp.WarpReductionEntry({identity}, {inputCount}, {scalarCount}, {execution});");
    }

    private static void Line(StringBuilder source, string value)
    {
        source.Append(value);
        source.Append('\n');
    }
}
